import type { TemplateRecord } from "./library";
import type { TemplateVerification } from "./provenance";

const RUNTIME_SHA256_BY_PATH: Record<string, string> = {
  "/templates/dang-sample.docx": "1abd2abe6a8912f07af4f4788be039ee107efd2e13758eb022e0726a9ea78f5e",
  "/templates/iemm/01-quyet-dinh-ca-biet.docx": "be284a9c372dd688ffb284581ea7aaf5e4f805e9dd2416f11c77c2264608fb00",
  "/templates/iemm/02-quyet-dinh-ban-hanh-van-ban.docx": "1f27ac28c500f3cb12a7728f4c325aa23d51e0ceff66d8cf3fc13e824800c7ce",
  "/templates/iemm/03-quy-che-quy-dinh.docx": "50ea561ecdef57299534670c96a08674f378fbf3cd227918e7c3c22b4762148b",
  "/templates/iemm/04-van-ban-ban-hanh-kem-theo-quyet-dinh.docx": "a26ebbe798d175e6e2337479b265818aaee4a0b992caed7d8a6cfacac75cf91a",
  "/templates/iemm/05-cong-van-hanh-chinh.docx": "9088dc7b279787a6b8f8391de4a17067e079e654493668fdd99e080522dad6f3",
  "/templates/iemm/06-thong-bao-noi-bo-vien.docx": "1941b475c557cb98be462dd4380c624d7efdf62950d8f0a736dd17a607a02270",
  "/templates/iemm/07-to-trinh-cua-vien.docx": "ac6faec89fc0fe336633d9560d494dd72b9064290cd78ecbe3009612a8aa8f16",
  "/templates/iemm/08-to-trinh-cua-don-vi-gui-vien.docx": "d403ca491efdcc4aa0bba39c7cda457d6e62dc72c8276d426675817a01625338",
  "/templates/iemm/09-bien-ban.docx": "dc96d8be0d172a2b9e3d05c8dd13ff8cebfee18f5cd06fb095c3e81ea7bfe761",
  "/templates/iemm/10-van-ban-chung.docx": "f1a07e1e982af0ac060540b32509b7e703d64a890e4fe3c58a23fdf1780a266f",
  "/templates/iemm/11-ban-sao-van-ban.docx": "38a25d81dae89a4207d5832963f06c689217ad8a324b10cc389271c3067daa7b",
  "/templates/iemm/12-thu-moi-hop.docx": "8c565c85deac2c38cd06878ab2cefc6256eebc00ab35d4b510495fadd73de933",
  "/templates/iemm/13-thu-bao-hoan-hop.docx": "55e13f1ab18f433bef053a66845b0196fd1b36b6616aeaa8b64f43e13c26cf34",
  "/templates/iemm/14-cong-van-dinh-chinh.docx": "a8e5e5ba4e32d5bd43de31a8493039755c12abccf234d06e4cc04028f6087c3e",
  "/templates/iemm-don-xin-nghi-phep-template.docx": "ecec4bdbd864cf0756d7ab7ec072f8e354c7878f041219be82cc80149fccfe1d",
  "/templates/tvci-cong-van-template.docx": "29bcd69b4cadeabcdeb7495507a1c382ff6a96086ed43114d1d034704e705fa1",
  "/templates/tvci-thong-bao-template.docx": "b53c35525ee2dd66b416143426adc556a2f61577ae3d0fb0ae17b0322a996c45",
  "/templates/tvci-sample.docx": "aac92663d74536c7534d2f7970b69bfc5275d4b823244963256c70c3da7f9a5a",
  "/templates/iemm-sample.docx": "b54d1edc4ff493370fe3555874ef252b4dad4f0bca97de467601b4ef3916ab9d",
};

const QUARANTINED_SAMPLE_IDS = new Set(["dang-sample-001", "iemm-sample-001", "tvci-sample-001"]);

function bundledVerification(id: string, runtimePath: string): TemplateVerification {
  const status = QUARANTINED_SAMPLE_IDS.has(id) ? "quarantined" : "unverified";
  return {
    status,
    reason: status === "quarantined"
      ? "Generic/sample DOCX retained for audit only; no official canonical DOCX is present."
      : "No exact official canonical DOCX is present in the repository. Reference titles and bundled files do not prove the approved form.",
    canonicalSource: null,
    runtime: { path: runtimePath, sha256: RUNTIME_SHA256_BY_PATH[runtimePath] ?? null },
  };
}

const IEMM_APPENDIX = "4. Mau Chi tiet van ban cua Vien (PLVII) Quy che van thu Vien.doc";
const IEMM_FONT_RULES = "3. Phu luc IV Chi tiet mau chu- Quy che van thu Vien.doc";
const IEMM_RULES = "1. Quy che Chinh ve Cong tac van thu cua Vien.doc";
const IEMM_SPECIAL = "4. Quy dinh rieng ve Van ban cua Vien.ppt";
const IEMM_GUIDE = "5. Van ban- Van thu (HD cu the tung loai van ban).ppt";
const IEMM_APPENDIX_VII = "Quy chế Văn thư của Viện (QĐ 731-2023), Phụ lục VII";
const iemmSourceReference = (sample: string) => `${IEMM_APPENDIX_VII} — ${sample}`;

const CATALOG_RECORDS: TemplateRecord[] = [
  {
    id: "dang-sample-001",
    name: "Văn bản Đảng mẫu",
    organization: "DANG",
    department: "Văn bản Đảng",
    documentType: "Nghị quyết",
    keywords: ["đảng", "nghị quyết", "chi bộ", "văn bản đảng"],
    version: "1.0",
    status: "active",
    description: "Biểu mẫu khởi tạo cho văn bản Đảng.",
    source: { kind: "bundled", path: "/templates/dang-sample.docx" },
    referenceSources: ["Hướng dẫn 05-HD/VPTW 2026"],
  },
  {
    id: "iemm-qd-001",
    name: "Quyết định cá biệt của Viện",
    organization: "IEMM",
    department: "Văn phòng",
    documentType: "Quyết định",
    keywords: ["iemm", "viện", "quyết định", "qđ-vcnm"],
    version: "1.0",
    status: "active",
    description: "Mẫu Quyết định cá biệt của Viện.",
    symbolHint: "Số: …/QĐ-VCNM",
    usageNotes: ["Tên loại văn bản in hoa, đậm; trích yếu cỡ 13, đậm, căn giữa.", "Nội dung quyết định bố cục theo Điều."],
    source: { kind: "bundled", path: "/templates/iemm/01-quyet-dinh-ca-biet.docx" },
    referenceSources: [IEMM_APPENDIX, IEMM_FONT_RULES, IEMM_GUIDE, iemmSourceReference("Mẫu Quyết định cá biệt")],
    sortOrder: 1,
  },
  {
    id: "iemm-qd-ban-hanh-001",
    name: "Quyết định ban hành hoặc phê duyệt văn bản của Viện",
    organization: "IEMM",
    department: "Văn phòng",
    documentType: "Quyết định",
    keywords: ["iemm", "quyết định", "ban hành", "phê duyệt", "quy chế", "kế hoạch"],
    version: "1.0",
    status: "active",
    description: "Mẫu quyết định ban hành hoặc phê duyệt quy chế, quy định, kế hoạch, đề án hoặc phương án.",
    symbolHint: "Số: …/QĐ-VCNM",
    usageNotes: ["Nêu rõ văn bản được ban hành hoặc phê duyệt kèm theo quyết định.", "Phân công trách nhiệm thực hiện ở điều khoản cuối."],
    source: { kind: "bundled", path: "/templates/iemm/02-quyet-dinh-ban-hanh-van-ban.docx" },
    referenceSources: [iemmSourceReference("Quyết định ban hành hoặc phê duyệt văn bản")],
    sortOrder: 2,
  },
  {
    id: "iemm-quy-che-001",
    name: "Quy chế, quy định của Viện",
    organization: "IEMM",
    department: "Dùng chung",
    documentType: "Quy chế",
    keywords: ["iemm", "quy chế", "quy định", "chương", "điều", "phạm vi áp dụng"],
    version: "1.0",
    status: "active",
    description: "Khung Quy chế hoặc quy định ban hành kèm theo quyết định của Viện.",
    usageNotes: ["Tổ chức nội dung theo Chương, Điều, Khoản, Điểm khi phù hợp.", "Bổ sung phạm vi áp dụng và trách nhiệm thực hiện trước khi ban hành."],
    source: { kind: "bundled", path: "/templates/iemm/03-quy-che-quy-dinh.docx" },
    referenceSources: [iemmSourceReference("Mẫu Quy chế, quy định")],
    sortOrder: 3,
  },
  {
    id: "iemm-van-ban-kem-quyet-dinh-001",
    name: "Văn bản ban hành kèm theo quyết định của Viện",
    organization: "IEMM",
    department: "Dùng chung",
    documentType: "Văn bản kèm quyết định",
    keywords: ["iemm", "văn bản kèm theo", "quyết định", "chương trình", "kế hoạch", "đề án", "phương án"],
    version: "1.0",
    status: "active",
    description: "Mẫu văn bản được ban hành hoặc phê duyệt kèm theo quyết định.",
    usageNotes: ["Dùng cho chương trình, kế hoạch, đề án, phương án và văn bản được phê duyệt.", "Bổ sung mục tiêu, tiến độ và tổ chức thực hiện theo nội dung thực tế."],
    source: { kind: "bundled", path: "/templates/iemm/04-van-ban-ban-hanh-kem-theo-quyet-dinh.docx" },
    referenceSources: [iemmSourceReference("Mẫu văn bản khác")],
    sortOrder: 4,
  },
  {
    id: "iemm-cv-001",
    name: "Công văn hành chính của Viện",
    organization: "IEMM",
    department: "Văn phòng",
    documentType: "Công văn",
    keywords: ["iemm", "viện", "công văn", "hành chính"],
    version: "1.1",
    status: "active",
    description: "Mẫu công văn hành chính của Viện.",
    symbolHint: "Số: …/VCNM-[ĐƠN VỊ]",
    usageNotes: ["Công văn không ghi chữ tắt CV trong số/ký hiệu.", "Trích yếu công văn cỡ 13, chữ thường, đứng, không đậm.", "Kính gửi cỡ 13; Nơi nhận tiêu đề cỡ 12 nghiêng đậm; đơn vị nhận cỡ 11."],
    source: { kind: "bundled", path: "/templates/iemm/05-cong-van-hanh-chinh.docx" },
    referenceSources: [IEMM_APPENDIX, IEMM_FONT_RULES, IEMM_RULES, IEMM_SPECIAL, iemmSourceReference("Mẫu Công văn hành chính")],
    sortOrder: 5,
  },
  {
    id: "iemm-tb-001",
    name: "Thông báo nội bộ của Viện",
    organization: "IEMM",
    department: "Văn phòng",
    documentType: "Thông báo",
    keywords: ["iemm", "thông báo", "nội bộ viện"],
    version: "1.1",
    status: "active",
    description: "Mẫu thông báo nội bộ của Viện.",
    symbolHint: "Số: …/TB-VCNM",
    usageNotes: ["Trích yếu thông báo cỡ 13, đậm, căn giữa, có dòng kẻ mảnh bên dưới.", "Số thông báo không kèm tên đơn vị soạn thảo."],
    source: { kind: "bundled", path: "/templates/iemm/06-thong-bao-noi-bo-vien.docx" },
    referenceSources: [IEMM_APPENDIX, IEMM_GUIDE, IEMM_FONT_RULES, iemmSourceReference("Mẫu Thông báo nội bộ Viện")],
    sortOrder: 6,
  },
  {
    id: "iemm-tt-001",
    name: "Tờ trình của Viện gửi cấp trên",
    organization: "IEMM",
    department: "Văn phòng",
    documentType: "Tờ trình",
    keywords: ["iemm", "tờ trình", "viện", "gửi cấp trên"],
    version: "1.1",
    status: "active",
    description: "Tờ trình chính thức của Viện gửi cấp trên.",
    symbolHint: "Số: …/TTr-VCNM",
    usageNotes: ["Phần 1 nêu lý do/cơ sở; Phần 2 nêu đề xuất/phương án và tính khả thi; Phần 3 nêu hiệu quả và kiến nghị.", "Trích yếu cỡ 13, đậm, căn giữa."],
    source: { kind: "bundled", path: "/templates/iemm/07-to-trinh-cua-vien.docx" },
    referenceSources: [IEMM_APPENDIX, IEMM_GUIDE, iemmSourceReference("Mẫu Tờ trình của Viện")],
    sortOrder: 7,
  },
  {
    id: "iemm-to-trinh-noi-bo-001",
    name: "Tờ trình của đơn vị gửi Viện",
    organization: "IEMM",
    department: "Dùng chung",
    documentType: "Tờ trình",
    keywords: ["tờ trình nội bộ", "đơn vị gửi viện", "trưởng phòng", "giám đốc trung tâm"],
    version: "1.0",
    status: "active",
    description: "Tờ trình nội bộ từ phòng/đơn vị/Trung tâm gửi Viện.",
    usageNotes: ["Mẫu nội bộ không lấy số văn bản, không đóng dấu Viện và không lưu tại Văn thư Viện.", "Có khối ký Người viết tờ trình (khi cần) và Trưởng đơn vị/KT. Trưởng đơn vị."],
    source: { kind: "bundled", path: "/templates/iemm/08-to-trinh-cua-don-vi-gui-vien.docx" },
    referenceSources: [IEMM_APPENDIX, iemmSourceReference("Mẫu Tờ trình của đơn vị gửi Viện")],
    sortOrder: 8,
  },
  {
    id: "iemm-bb-001",
    name: "Biên bản của Viện",
    organization: "IEMM",
    department: "Văn phòng",
    documentType: "Biên bản",
    keywords: ["iemm", "biên bản", "họp", "chủ trì", "thư ký"],
    version: "1.1",
    status: "active",
    description: "Mẫu biên bản cuộc họp/buổi làm việc của Viện.",
    symbolHint: "Số: …/BB-VCNM",
    usageNotes: ["Biên bản quan trọng ghi số lưu Văn thư và đóng dấu cơ quan.", "Bắt buộc có chữ ký của chủ trì và thư ký; khối CHỦ TRÌ không ghi lại chức vụ vì phần đầu đã nêu."],
    source: { kind: "bundled", path: "/templates/iemm/09-bien-ban.docx" },
    referenceSources: [IEMM_APPENDIX, iemmSourceReference("Mẫu Biên bản")],
    sortOrder: 9,
  },
  {
    id: "iemm-ban-sao-001",
    name: "Bản sao văn bản của Viện",
    organization: "IEMM",
    department: "Văn phòng",
    documentType: "Bản sao",
    keywords: ["iemm", "bản sao", "sao y", "trích sao", "sao lục"],
    version: "1.0",
    status: "active",
    description: "Mẫu bản sao dùng cho sao y bản chính, trích sao hoặc sao lục văn bản.",
    usageNotes: ["Ghi rõ loại bản sao và nội dung văn bản gốc.", "Kiểm tra thẩm quyền người ký bản sao trước khi sử dụng."],
    source: { kind: "bundled", path: "/templates/iemm/11-ban-sao-van-ban.docx" },
    referenceSources: [iemmSourceReference("Mẫu Bản sao văn bản")],
    sortOrder: 11,
  },
  {
    id: "iemm-thu-moi-001",
    name: "Thư mời họp của Viện",
    organization: "IEMM",
    department: "Văn phòng",
    documentType: "Thư mời",
    keywords: ["thư mời", "mời họp", "hội nghị", "iemm"],
    version: "1.0",
    status: "active",
    description: "Thư mời có bản lưu văn thư, dùng khi tính chất trang trọng/quan trọng.",
    symbolHint: "Số: …/MH-VCNM",
    usageNotes: ["Trích yếu thư mời cỡ 13, chữ thường, đứng, không đậm.", "Nêu rõ chủ trì, thời gian, địa điểm, chuẩn bị báo cáo và đề nghị/ghi chú."],
    source: { kind: "bundled", path: "/templates/iemm/12-thu-moi-hop.docx" },
    referenceSources: [IEMM_APPENDIX, iemmSourceReference("Mẫu thư mời họp")],
    sortOrder: 12,
  },
  {
    id: "iemm-thu-hoan-hop-001",
    name: "Thư báo hoãn họp của Viện",
    organization: "IEMM",
    department: "Văn phòng",
    documentType: "Thư báo hoãn họp",
    keywords: ["iemm", "hoãn họp", "thay đổi lịch họp", "thư báo"],
    version: "1.0",
    status: "active",
    description: "Mẫu thư báo hoãn hoặc thay đổi lịch, địa điểm cuộc họp đã mời.",
    usageNotes: ["Nêu rõ giấy mời hoặc cuộc họp liên quan.", "Ghi lịch mới hoặc hướng dẫn thông báo sau khi có lịch chính thức."],
    source: { kind: "bundled", path: "/templates/iemm/13-thu-bao-hoan-hop.docx" },
    referenceSources: [iemmSourceReference("Mẫu báo hoãn họp")],
    sortOrder: 13,
  },
  {
    id: "iemm-cong-van-dinh-chinh-001",
    name: "Công văn đính chính văn bản của Viện",
    organization: "IEMM",
    department: "Văn phòng",
    documentType: "Công văn đính chính",
    keywords: ["iemm", "công văn", "đính chính", "sai sót", "văn bản đã ban hành"],
    version: "1.0",
    status: "active",
    description: "Mẫu công văn đính chính sai sót trong văn bản đã ban hành.",
    symbolHint: "Số: …/VCNM-[ĐƠN VỊ]",
    usageNotes: ["Dẫn chính xác văn bản gốc cần đính chính.", "Nêu rõ nội dung đã ghi và nội dung đúng thay thế."],
    source: { kind: "bundled", path: "/templates/iemm/14-cong-van-dinh-chinh.docx" },
    referenceSources: [IEMM_APPENDIX, IEMM_RULES, iemmSourceReference("Mẫu công văn đính chính văn bản")],
    sortOrder: 14,
  },
  {
    id: "iemm-van-ban-co-ten-loai-001",
    name: "Văn bản hành chính chung của Viện",
    organization: "IEMM",
    department: "Dùng chung",
    documentType: "Văn bản có tên loại",
    keywords: ["kế hoạch", "báo cáo", "chương trình", "phương án", "đề án", "công điện"],
    version: "1.0",
    status: "active",
    description: "Mẫu chung cho kế hoạch, báo cáo, chương trình, phương án, đề án, công điện và các văn bản có tên loại.",
    symbolHint: "Số: …/[LOẠI]-VCNM",
    usageNotes: ["Tên loại in hoa, đậm; trích yếu cỡ 13, đậm, căn giữa.", "Ví dụ: /BC-VCNM cho Báo cáo, /KH-VCNM cho Kế hoạch."],
    source: { kind: "bundled", path: "/templates/iemm/10-van-ban-chung.docx" },
    referenceSources: [IEMM_APPENDIX, IEMM_FONT_RULES, iemmSourceReference("Mẫu văn bản chung")],
    sortOrder: 10,
  },
  {
    id: "iemm-bao-cao-001",
    name: "Khung Báo cáo của Viện",
    organization: "IEMM",
    department: "Dùng chung",
    documentType: "Báo cáo",
    keywords: ["iemm", "báo cáo", "bc-vcnm", "kết quả thực hiện"],
    version: "1.0",
    status: "active",
    description: "Khung Báo cáo dùng chung, kế thừa mẫu văn bản có tên loại của Viện.",
    symbolHint: "Số: …/BC-VCNM",
    usageNotes: ["Bổ sung phạm vi, số liệu và căn cứ thực tế trước khi phát hành; add-in không tự sinh số liệu."],
    source: { kind: "bundled", path: "/templates/iemm/10-van-ban-chung.docx" },
    referenceSources: [IEMM_APPENDIX, IEMM_FONT_RULES, iemmSourceReference("Mẫu văn bản chung cho Báo cáo")],
    sortOrder: 20,
  },
  {
    id: "iemm-ke-hoach-001",
    name: "Khung Kế hoạch của Viện",
    organization: "IEMM",
    department: "Dùng chung",
    documentType: "Kế hoạch",
    keywords: ["iemm", "kế hoạch", "kh-vcnm", "tiến độ", "phân công"],
    version: "1.0",
    status: "active",
    description: "Khung Kế hoạch dùng chung, kế thừa mẫu văn bản có tên loại của Viện.",
    symbolHint: "Số: …/KH-VCNM",
    usageNotes: ["Bổ sung mục tiêu, tiến độ, phân công và nguồn lực thực tế trước khi phát hành; không tự bịa dữ kiện."],
    source: { kind: "bundled", path: "/templates/iemm/10-van-ban-chung.docx" },
    referenceSources: [IEMM_APPENDIX, IEMM_FONT_RULES, iemmSourceReference("Mẫu văn bản chung cho Kế hoạch")],
    sortOrder: 21,
  },
  {
    id: "iemm-nghi-phep-001",
    name: "Đơn xin nghỉ phép của Viện",
    organization: "IEMM",
    department: "Tổ chức - Hành chính",
    documentType: "Đơn nghỉ phép",
    keywords: ["đơn xin nghỉ phép", "nghỉ phép", "viện"],
    version: "1.0",
    status: "active",
    description: "Biểu mẫu đơn xin nghỉ phép theo mẫu Viện.",
    source: { kind: "bundled", path: "/templates/iemm-don-xin-nghi-phep-template.docx" },
    referenceSources: ["Mau don xin nghi- Ky HD.doc"],
  },
  {
    id: "tvci-cv-001",
    name: "Công văn của Trung tâm Thử nghiệm - Kiểm định Công nghiệp",
    organization: "TVCI",
    department: "Văn bản chung",
    documentType: "Công văn",
    keywords: ["công văn", "tttn", "vcnm-tttn", "trung tâm thử nghiệm kiểm định công nghiệp"],
    version: "1.1",
    status: "active",
    description: "Công văn do Trung tâm Thử nghiệm - Kiểm định Công nghiệp chủ trì soạn thảo nhưng phát hành dưới danh nghĩa Viện Cơ khí Năng lượng và Mỏ - Vinacomin theo quy định riêng của Viện.",
    symbolHint: "Số: …/VCNM-TTTN",
    usageNotes: ["Không ghi chữ CV trong số công văn.", "Quy định riêng của Viện Cơ khí Năng lượng và Mỏ - Vinacomin quy định công văn do Trung tâm Thử nghiệm - Kiểm định Công nghiệp soạn thảo dùng /VCNM-TTTN."],
    source: { kind: "bundled", path: "/templates/tvci-cong-van-template.docx" },
    referenceSources: [IEMM_SPECIAL, IEMM_APPENDIX, IEMM_FONT_RULES, IEMM_RULES],
  },
  {
    id: "tvci-tb-001",
    name: "Thông báo của Trung tâm Thử nghiệm - Kiểm định Công nghiệp",
    organization: "TVCI",
    department: "Văn bản chung",
    documentType: "Thông báo",
    keywords: ["thông báo", "văn bản chung", "tb-vcnm", "trung tâm thử nghiệm kiểm định công nghiệp"],
    version: "1.1",
    status: "active",
    description: "Thông báo do Trung tâm Thử nghiệm - Kiểm định Công nghiệp chuẩn bị, sử dụng thể thức văn bản của Viện Cơ khí Năng lượng và Mỏ - Vinacomin.",
    symbolHint: "Số: …/TB-VCNM",
    usageNotes: ["Quy định nguồn nêu số Thông báo dùng /TB-VCNM, không kèm tên đơn vị soạn thảo."],
    source: { kind: "bundled", path: "/templates/tvci-thong-bao-template.docx" },
    referenceSources: [IEMM_APPENDIX, IEMM_FONT_RULES, IEMM_SPECIAL],
  },
  {
    id: "tvci-sample-001",
    name: "Biểu mẫu chung của Trung tâm Thử nghiệm - Kiểm định Công nghiệp",
    organization: "TVCI",
    department: "Văn bản chung",
    documentType: "Biểu mẫu",
    keywords: ["mẫu", "biểu mẫu", "văn bản chung", "trung tâm thử nghiệm kiểm định công nghiệp"],
    version: "1.0",
    status: "active",
    description: "Mẫu khởi tạo chung cho Trung tâm Thử nghiệm - Kiểm định Công nghiệp.",
    source: { kind: "bundled", path: "/templates/tvci-sample.docx" },
    referenceSources: [IEMM_FONT_RULES],
  },
  {
    id: "iemm-sample-001",
    name: "Biểu mẫu chung của Viện Cơ khí Năng lượng và Mỏ - Vinacomin",
    organization: "IEMM",
    department: "Dùng chung",
    documentType: "Biểu mẫu",
    keywords: ["mẫu", "biểu mẫu", "viện cơ khí năng lượng và mỏ"],
    version: "1.0",
    status: "active",
    description: "Mẫu khởi tạo chung cho Viện Cơ khí Năng lượng và Mỏ - Vinacomin.",
    source: { kind: "bundled", path: "/templates/iemm-sample.docx" },
    referenceSources: [IEMM_RULES],
  },
];

export const TEMPLATE_CATALOG: TemplateRecord[] = CATALOG_RECORDS.map((record) => ({
  ...record,
  verification: record.source.kind === "bundled"
    ? bundledVerification(record.id, record.source.path)
    : undefined,
}));

