/**
 * Cleans extra spaces (multiple spaces to single) and trims the text.
 */
export function cleanExtraSpaces(text: string): string {
  return text.replace(/[ \t]{2,}/g, " ").trim();
}

/**
 * Normalizes punctuation spacing.
 * - Removes space before , . ; : ! ?
 * - Adds space after punctuation if missing (except inside numbers/decimals like 3.14)
 */
export function normalizePunctuation(text: string): string {
  let res = text;
  // Remove spaces before punctuation
  res = res.replace(/\s+([,.;:!?])/g, "$1");
  // Add space after punctuation if followed by a letter (avoiding decimals or dots inside words/acronyms)
  res = res.replace(/([,;:!?])([a-zA-ZÀ-ỹ])/g, "$1 $2");
  // For dots, it's a bit trickier because of abbreviations. We'll do a safe assumption: if followed by uppercase or another word char.
  res = res.replace(/(\.)([A-ZÀ-Ỹ])/g, "$1 $2");
  return res;
}

/**
 * Replaces vertical tabs (\v or \x0B, often generated by Shift+Enter in Word) with a space.
 */
export function fixManualLineBreaks(text: string): string {
  return text.replace(/\s*[\v\x0B]\s*/g, " ");
}
