import type { KnowledgeRecord } from "./models";

export const SEED_KNOWLEDGE_RECORDS: KnowledgeRecord[] = [
  {
    id: "kb-header-tvci",
    title: "Tiêu đề header 2 cấp văn bản Trung tâm TVCI",
    content: "Văn bản do Trung tâm hoặc các phòng thuộc Trung tâm ban hành: header bắt buộc 2 cấp gồm VIỆN CƠ KHÍ NĂNG LƯỢNG VÀ MỎ - VINACOMIN và TRUNG TÂM THỬ NGHIỆM - KIỂM ĐỊNH CÔNG NGHIỆP. Tuyệt đối không đưa tên phòng ban thành cấp thứ ba trong header. Tên phòng chỉ xuất hiện tại các vị trí nghiệp vụ phù hợp như đơn vị soạn thảo, nơi nhận, chữ ký.",
    category: "mandatory",
    scope: "TVCI",
    tags: ["header", "tiêu đề", "cấp viện", "tvci", "phòng ban"],
    referenceSource: "Quy định thể thức văn bản nội bộ TVCI - IEMM",
    exampleSnippet: "VIỆN CƠ KHÍ NĂNG LƯỢNG VÀ MỎ - VINACOMIN\nTRUNG TÂM THỬ NGHIỆM - KIỂM ĐỊNH CÔNG NGHIỆP",
  },
  {
    id: "kb-header-iemm",
    title: "Tiêu đề header 2 cấp văn bản Viện Cơ khí",
    content: "Văn bản cấp Viện: header gồm 2 cấp: TẬP ĐOÀN CÔNG NGHIỆP THAN - KHOÁNG SẢN VIỆT NAM và VIỆN CƠ KHÍ NĂNG LƯỢNG VÀ MỎ - VINACOMIN.",
    category: "mandatory",
    scope: "IEMM",
    tags: ["header", "tiêu đề", "viện cơ khí", "iemm", "tập đoàn"],
    referenceSource: "Quy định văn bản Vinacomin",
    exampleSnippet: "TẬP ĐOÀN CÔNG NGHIỆP THAN - KHOÁNG SẢN VIỆT NAM\nVIỆN CƠ KHÍ NĂNG LƯỢNG VÀ MỎ - VINACOMIN",
  },
  {
    id: "kb-addressee-single-multi",
    title: "Quy tắc trình bày khối Kính gửi (1 nơi vs nhiều nơi)",
    content: "Nếu chỉ gửi 1 nơi: ghi cùng dòng với chữ Kính gửi (VD: Kính gửi: Tập đoàn Công nghiệp Than - Khoáng sản Việt Nam). Nếu gửi từ 2 nơi trở lên: xuống dòng, mỗi nơi một dòng có dấu gạch đầu dòng căn lề đều.",
    category: "mandatory",
    scope: "COMMON",
    tags: ["kính gửi", "addressee", "nghị định 30", "nơi nhận"],
    referenceSource: "Nghị định 30/2020/NĐ-CP Điều 10",
    exampleSnippet: "Kính gửi:\n- Tập đoàn Công nghiệp Than - Khoáng sản Việt Nam;\n- Công ty Cổ phần Than Đèo Nai.",
  },
  {
    id: "kb-horizontal-rules",
    title: "Độ dài đường kẻ ngang Quốc hiệu & Cơ quan",
    content: "Đường kẻ dưới Quốc ngữ ('Độc lập - Tự do - Hạnh phúc') dài bằng 1/3 đến 1/2 độ dài dòng chữ. Đường kẻ dưới Tên cơ quan ban hành dài bằng 1/3 đến 1/2 độ dài tên dòng cơ quan.",
    category: "guideline",
    scope: "COMMON",
    tags: ["đường kẻ", "vạch kẻ", "quốc hiệu", "thể thức"],
    referenceSource: "Nghị định 30/2020/NĐ-CP Phụ lục I",
  },
  {
    id: "kb-date-position",
    title: "Căn lề và khoảng cách khối Địa danh - Ngày tháng",
    content: "Khối ngày tháng năm căn lề phải, cách lề phải chuẩn (15mm), hạ xuống 1 dòng so với Quốc hiệu nếu bên khối cơ quan có 2 cấp.",
    category: "guideline",
    scope: "COMMON",
    tags: ["ngày tháng", "địa danh", "căn lề", "khoảng cách"],
    referenceSource: "Quy chế văn thư lưu trữ Vinacomin",
  },
  {
    id: "kb-recipients-t2",
    title: "Ký hiệu viết tắt tên Trung tâm ở phần Nơi nhận",
    content: "Ở phần Nơi nhận cuối văn bản, viết tắt tên Trung tâm thành T2 (theo cách gọi quy ước nội bộ của Viện).",
    category: "experience",
    scope: "TVCI",
    tags: ["nơi nhận", "viết tắt", "T2", "trung tâm"],
    referenceSource: "Quy ước soạn thảo nội bộ Viện",
    exampleSnippet: "Nơi nhận:\n- Như trên;\n- Viện trưởng (để b/c);\n- GĐ T2;\n- Lưu: VT, T2.",
  },
  {
    id: "kb-phrase-contract-basis",
    title: "Mở đầu căn cứ Hợp đồng dịch vụ thử nghiệm / kiểm định",
    content: "Cụm từ chuẩn mở đầu trong các Tờ trình, Biên bản, Báo cáo kỹ thuật của Trung tâm.",
    category: "phrase",
    scope: "TVCI",
    tags: ["mẫu câu", "căn cứ", "hợp đồng", "thử nghiệm", "kiểm định"],
    referenceSource: "Mẫu báo cáo TVCI",
    exampleSnippet: "Căn cứ Hợp đồng dịch vụ thử nghiệm / kiểm định số ... ký ngày ... giữa Trung tâm Thử nghiệm - Kiểm định Công nghiệp và ...",
  },
  {
    id: "kb-phrase-legal-standards",
    title: "Mẫu viện dẫn Quy chuẩn kỹ thuật quốc gia QCVN / TCVN",
    content: "Cách viết chuẩn các căn cứ quy chuẩn an toàn mỏ và thiết bị công nghiệp.",
    category: "phrase",
    scope: "COMMON",
    tags: ["mẫu câu", "qcvn", "tcvn", "tiêu chuẩn"],
    referenceSource: "Hệ thống QCVN/TCVN Vinacomin",
    exampleSnippet: "Căn cứ Quy chuẩn kỹ thuật quốc gia về an toàn trong khai thác than hầm lò (QCVN 01:2011/BCT);",
  },
];
